export default {
  login: {
    mainTitle: 'Welcome Back!',
    forgotPassword: 'Forgot password',
    logIn: ' Log in',
    dontHaveAcc: 'Don’t have an account?',
    signUp: ' Sign Up',
    placeHolderEmail: 'Enter your e-mail',
    placeHolderPassword: 'Enter password',
  },
  welcome: {
    mainTitle: 'Gets things done with ToDoApp!',
    mainText1: 'ToDoApp is a task manager that helps you get ',
    mainText2: 'things done, manage your time and  ',
    mainText3: 'be more productive.',
    mainText4: "It's simple, fast and easy to use.",
    btnStarted: 'Get Started',
  },
  register: {
    mainTitle: 'Welcome Onboard!',
    mainText: 'Lets help you meet up your tasks.',
    registerBtn: 'Register',
    highlightedText: 'Already have an account?',
    placeHolderName: 'Enter your full name',
    placeHolderConfirmPassword: 'Confirm password',
  },
  message: {
    name: 'Name must be at least 7 characters long',
    email: 'Email must be a valid email address',
    password: 'Password must be at least 8 characters long',
    confirmPassword: 'Passwords must match',
    forgetPassword:
      'You will receive a link to create a new password via email.',
    valid: 'Valid information',
    invalid: 'Invalid information',
    sended: 'Information sent',
    nouser: 'User not found',
    error: 'An error has occurred',
    avatar: 'Avatar changed successfully',
    avatarError: "Avatar couldn't be changed, please try again",
    taskUpdated: 'Task updated successfully',
    taskDeleted: 'Task deleted successfully',
    taskCreated: 'Task created successfully',
    logOut: 'Log out successfully',
    logIn: 'Log in successfully',
    noPassword: 'Password is required',
    noEmail: 'Email is required',
    emptyFields: 'All fields are required',
    register: 'Register successfully',
    invalidUserInformation: 'Invalid user information',
    passwordNotMatch: 'Passwords do not match',
    invalidPassword: 'Password does not respect the requirements',
    invalidEmail: 'Invalid email',
    invalidName: 'Invalid name',
    welome: 'Welcome',
  },
  tasks: {
    createName: 'My Tasks',
    createBtn: 'Create',
    createDescription: 'Create a new task',
    mainTitle: 'Add a new task',
    noTasks: 'No tasks added yet',
  },
};
